Add support for write protected LUNs.
adafruit/asf4 pull request #4
Opened 2017-10-28 00:01 UTC by tannewt

2017-10-28 03:26 UTC, dhalbert requested changes
More common spelling is "writable". Code looks great!

2017-10-28 03:26 UTC, dhalbert commented on samd21/usb/class/msc/device/mscdf.c
> +		mscdf_is_writeable = (mscdf_is_writeable_t)func;
Two spellings of writable here: https://m-w.com and the online OED only give "writable" as the spelling (don't list the other as a variant.

2017-10-29 23:50 UTC, tannewt commented
Please take another look!

2017-10-30 02:04 UTC, dhalbert approved these changes

2017-10-30 02:05 UTC, merged